In [10]:
lazy import pandas as pd
lazy from scipy import stats

lazy from common import data_folder, get_material_names

In [11]:
# 材料名称按稀有度（白/绿/蓝）从物品数据中获取
item_names_T1 = get_material_names(0)
item_names_T2 = get_material_names(1)
item_names_T3 = get_material_names(2)

In [12]:
df_T3 = pd.read_csv(
    data_folder / "掉单一蓝材料的活动.csv", index_col=0, parse_dates=["作战开放时间"]
)
df_T2 = pd.read_csv(
    data_folder / "掉两种绿材料的活动.csv", index_col=0, parse_dates=["作战开放时间"]
)
df_T1 = pd.read_csv(
    data_folder / "掉全部白材料的活动.csv", index_col=0, parse_dates=["作战开放时间"]
)

In [13]:
times_threshold = 50000
stage_blacklist = []
zone_blacklist = ["崔林特尔梅之金", "覆潮之下・复刻", "孤星・复刻", "崔林特尔梅之金・复刻", "红丝绒"]

In [14]:
# 卡方检验


def chi2_test(作战理智消耗, 掉落数, 样本数):
    p = 掉落数.sum() / (样本数 * 作战理智消耗).sum()
    return stats.chisquare(掉落数, p * 样本数 * 作战理智消耗)

In [15]:
# 掉单一蓝材料的活动，按物品分组

df_T3_filtered = df_T3[~df_T3["作战名称"].isin(stage_blacklist)]
df_T3_filtered = df_T3_filtered[~df_T3_filtered["活动名称"].isin(zone_blacklist)]
df_T3_filtered = df_T3_filtered[df_T3_filtered["样本数"] >= times_threshold]

records = []
for item_name, group in sorted(
    df_T3_filtered.groupby("作战掉落物品名称"), key=lambda x: item_names_T3.index(x[0])
):
    总掉落数 = group["掉落数"].sum()
    总样本数 = group["样本数"].sum()
    总消耗理智 = (group["样本数"] * group["作战理智消耗"]).sum()
    单位理智掉落物品数量 = 总掉落数 / 总消耗理智
    单件期望理智 = 1 / 单位理智掉落物品数量
    chi2, p_value = chi2_test(group["作战理智消耗"], group["掉落数"], group["样本数"])
    records.append(
        {
            "作战掉落物品名称": item_name,
            "总掉落数": 总掉落数,
            "总样本数": 总样本数,
            "总消耗理智": 总消耗理智,
            "单位理智掉落物品数量": 单位理智掉落物品数量,
            "单件期望理智": 单件期望理智,
            "卡方检验p值": p_value,
        }
    )

df_T3_material = pd.DataFrame.from_records(records)
df_T3_material

,作战掉落物品名称,总掉落数,总样本数,总消耗理智,单位理智掉落物品数量,单件期望理智,卡方检验p值
0,固源岩组,41045073,37520702,787934742,0.052092,19.196817,9.999742e-01
1,糖组,28961810,30140583,625854432,0.046276,21.609645,9.999761e-01
2,聚酸酯组,16269615,16755921,351560547,0.046278,21.608412,9.948664e-01
3,异铁组,33463638,42998334,902965014,0.037060,26.983468,9.520476e-01
4,酮凝集组,26642323,34245492,718971747,0.037056,26.986076,4.220960e-01
5,全新装置,13950353,24308200,502533111,0.027760,36.022967,2.471073e-01
6,扭转醇,19760332,21541985,450668631,0.043847,22.806734,9.785699e-01
7,轻锰矿,24078461,31042641,649692597,0.037061,26.982314,3.677156e-02
8,研磨石,28130070,42753499,873734433,0.032195,31.060514,3.012184e-15
9,RMA70-12,30860361,52955544,1112066424,0.027750,36.035431,2.671263e-05
10,凝胶,35241952,50189014,1053969294,0.033437,29.906666,2.370031e-01
11,炽合金,32443231,38951056,817972176,0.039663,25.212414,9.910709e-01
12,晶体元件,23947395,27392457,574815984,0.041661,24.003278,9.447857e-01
13,半自然溶剂,5659100,8068064,169429344,0.033401,29.939274,1.408110e-02
14,化合切削液,13269782,18899800,396895800,0.033434,29.909745,1.677313e-01
15,转质盐组,4937088,7905257,166010397,0.029740,33.625165,9.128050e-01
16,褐素纤维,12365649,19085219,400789599,0.030853,32.411530,9.791501e-01
17,环烃聚质,9400333,16130325,338736825,0.027751,36.034556,6.793998e-01
18,类凝结核,12986206,18491601,388323621,0.033442,29.902777,8.639265e-01
19,液化高能气体,878709,1407416,29555736,0.029731,33.635408,0.000000e+00

In [16]:
# 掉两种绿材料的活动，按主掉落分组

df_T2_filtered = df_T2[~df_T2["作战名称"].isin(stage_blacklist)]
df_T2_filtered = df_T2_filtered[~df_T2_filtered["活动名称"].isin(zone_blacklist)]
df_T2_filtered = df_T2_filtered[df_T2_filtered["样本数"] >= times_threshold]

records = []
for item_name, group in sorted(
    df_T2_filtered.groupby("主掉落物品名称"), key=lambda x: item_names_T2.index(x[0])
):
    总掉落数 = group["主掉落数"].sum()
    总样本数 = group["样本数"].sum()
    总消耗理智 = (group["样本数"] * group["作战理智消耗"]).sum()
    单位理智掉落物品数量 = 总掉落数 / 总消耗理智
    单件期望理智 = 1 / 单位理智掉落物品数量
    chi2, p_value = chi2_test(group["作战理智消耗"], group["主掉落数"], group["样本数"])
    records.append(
        {
            "主掉落物品名称": item_name,
            "总掉落数": 总掉落数,
            "总样本数": 总样本数,
            "总消耗理智": 总消耗理智,
            "单位理智主掉落数量": 单位理智掉落物品数量,
            "单件期望理智": 单件期望理智,
            "卡方检验p值": p_value,
        }
    )

df_T2_material_main = pd.DataFrame.from_records(records)
df_T2_material_main

  主掉落物品名称       总掉落数      总样本数      总消耗理智  单位理智主掉落数量     单件期望理智    卡方检验p值
0     固源岩  133220069  75394653  959090100   0.138903   7.199291  0.999923
1       糖   36460627  32503989  393806691   0.092585  10.800875  0.999935
2     聚酸酯    3073024   2751068   33191898   0.092584  10.801054  0.999990
3      异铁    4776650   5305588   64490277   0.074068  13.501152  0.999645
4     酮凝集    8046141   9018311  108637683   0.074064  13.501837  0.999721
5      装置   30586354  45501141  546868539   0.055930  17.879494  0.000006

In [17]:
# 掉两种绿材料的活动，按副掉落分组

records = []
for item_name, group in sorted(
    df_T2_filtered.groupby("副掉落物品名称"), key=lambda x: item_names_T2.index(x[0])
):
    总掉落数 = group["副掉落数"].sum()
    总样本数 = group["样本数"].sum()
    总消耗理智 = (group["样本数"] * group["作战理智消耗"]).sum()
    单位理智掉落物品数量 = 总掉落数 / 总消耗理智
    单件期望理智 = 1 / 单位理智掉落物品数量
    chi2, p_value = chi2_test(group["作战理智消耗"], group["副掉落数"], group["样本数"])
    records.append(
        {
            "副掉落物品名称": item_name,
            "总掉落数": 总掉落数,
            "总样本数": 总样本数,
            "总消耗理智": 总消耗理智,
            "单位理智副掉落数量": 单位理智掉落物品数量,
            "单件期望理智": 单件期望理智,
            "卡方检验p值": p_value,
        }
    )

df_T2_material_sub = pd.DataFrame.from_records(records)
df_T2_material_sub

  副掉落物品名称      总掉落数      总样本数      总消耗理智  单位理智副掉落数量     单件期望理智        卡方检验p值
0     固源岩  50359056  60135846  725563929   0.069407  14.407814  9.999992e-01
1       糖  12818136  23054046  276648552   0.046334  21.582588  9.488892e-01
2     聚酸酯  12956556  23282435  279632217   0.046334  21.582295  9.827264e-01
3      异铁  17117584  33944141  462125646   0.037041  26.997130  1.303903e-01
4     酮凝集  11108047  24969091  300207408   0.037001  27.026120  9.653323e-01
5      装置   1713012   5089191   61907436   0.027671  36.139523  3.072652e-63

In [18]:
# 掉白材料的活动

df_T1_filtered = df_T1[~df_T1["作战名称"].isin(stage_blacklist)]
df_T1_filtered = df_T1_filtered[~df_T1_filtered["活动名称"].isin(zone_blacklist)]
df_T1_filtered = df_T1_filtered[df_T1_filtered["样本数"] >= times_threshold]

records = []
for item_name in item_names_T1:
    总掉落数 = df_T1_filtered[f"{item_name}掉落数"].sum()
    总样本数 = df_T1_filtered["样本数"].sum()
    总消耗理智 = (df_T1_filtered["样本数"] * df_T1_filtered["作战理智消耗"]).sum()
    单位理智掉落物品数量 = 总掉落数 / 总消耗理智
    单件期望理智 = 1 / 单位理智掉落物品数量
    chi2, p_value = chi2_test(
        df_T1_filtered["作战理智消耗"],
        df_T1_filtered[f"{item_name}掉落数"],
        df_T1_filtered["样本数"],
    )
    records.append(
        {
            "物品名称": item_name,
            "总掉落数": 总掉落数,
            "总样本数": 总样本数,
            "总消耗理智": 总消耗理智,
            "单位理智掉落物品数量": 单位理智掉落物品数量,
            "单件期望理智": 单件期望理智,
            "卡方检验p值": p_value,
        }
    )

df_material = pd.DataFrame.from_records(records)
df_material

   物品名称     总掉落数     总样本数     总消耗理智  单位理智掉落物品数量     单件期望理智        卡方检验p值
0    源岩  2201592  3517597  31658373    0.069542  14.379764  8.382131e-07
1    代糖  1467139  3517597  31658373    0.046343  21.578305  1.067827e-04
2   酯原料  1465476  3517597  31658373    0.046290  21.602792  4.716298e-06
3  异铁碎片  1171498  3517597  31658373    0.037004  27.023839  2.824422e-06
4    双酮  1168702  3517597  31658373    0.036916  27.088490  3.983989e-07
5  破损装置   878147  3517597  31658373    0.027738  36.051337  1.447835e-08